### ISSUE TITLE
Can Moonbit support run WASM programs in Cloud? 

### ISSUE THREAD

**Issue by rts-gordon** [moonbitlang/moonbit-docs#105]
Can Moonbit support run WASM programs written with Moonbit in Cloud?  like [Fermyon Cloud](https://www.fermyon.com/cloud). 

 Thank you.

**Comment by Yoorkin** [comment]
Yes, we have plans to support running WASM programs written with Moonbit on cloud platforms like Fermyon Cloud in the future. Thanks for your interest.
