### ISSUE TITLE
Type parameter bounds

### ISSUE THREAD

**Issue by jayphelps** [moonbitlang/moonbit-docs#121]
Is there any current support for specifying generic type requirements, sometimes referred to as bounded polymorphism, etc.

I've found Rust-style `[T: Eq]` seems to be supported for functions, but for type declarations I receive the error: `cannot declare constraints on parameters of type declaration` so that sounds like it's just not a feature yet for types. Wanted to confirm.

Also, are you wanting feedback at this stage or will be be too overwhelming to constantly hear my thoughts on missing things? e.g. ability to upgrade cli, incompatible behaviors between vscode formatter vs. compiler, etc.

**Comment by jayphelps** [comment]
FWIW once I noticed I _can_ do it on methods, I no longer have an immediate use case for it on the type declaration itself (for now). e.g. this is fine: `fn contains[T: Eq](self: Set[T], element: T) -> Bool {`

**Comment by bobzhang** [comment]
Indeed, do you have use cases for adding it for types?

**Comment by jayphelps** [comment]
I thought I did, but turns out having it methods was good enough for my current use case. If it actually does come up for real I'll come back. Thanks.
