### ISSUE TITLE
Code language not supported or define

### ISSUE THREAD

**Issue by L-mastershibo** [moonbitlang/moonbit-docs#126]
Code language not supported or defined. from Code Runner ,How to Run this code by configing vscode?

**Comment by Yoorkin** [comment]
Running a single .mbt file with moon build is not yet supported. Therefore, I think it's not possible to do this by configuring vscode (or any other vscode extension) without the `moon.pkg.json` and `moon.mod.json` files. If you don't want to deal with those files, try our [MoonBit playground](https://try.moonbitlang.com/)

**Comment by L-mastershibo** [comment]
thanks




??O(∩_∩)O~
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "moonbitlang/moonbit-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月21日(星期四) 中午1:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [moonbitlang/moonbit-docs] Code language not supported or define (Issue #126)





 
Running a single .mbt file with moon build is not yet supported. Therefore, I think it's not possible to do this by configuring vscode (or any other vscode extension) without the moon.pkg.json and moon.mod.json files. If you don't want to deal with those files, try our MoonBit playground
