### ISSUE TITLE
proposal for allowing braces to be optionally omitted for single statements

### ISSUE THREAD

**Issue by panicfrog** [moonbitlang/moonbit-docs#138]
<img width="616" alt="IMG_2129" src="https://github.com/moonbitlang/moonbit-docs/assets/53246970/f5e203ad-06da-46a5-9da5-62b74a19763e">

In Moonbit programming, there's an existing requirement for using explicit braces `{}` around control statements such as `break` even when they are the only statement within their scope. This is not aligned with more modern languages that allow omitting braces for single statements to reduce verbosity. I propose that Moonbit adopts a similar rule that permits the omission of braces around single statements (`break`, `continue`, `return`, etc.) when they are the only statement within braces. This change would streamline code readability and writing efficiency.

**Comment by bobzhang** [comment]
This was supported
