### ISSUE TITLE
Dyn trait support inside data structures, like Vectors

### ISSUE THREAD

**Issue by jayphelps** [moonbitlang/moonbit-docs#148]
I'm trying to be able to make data structures which can contain references to other data structures that implement a certain trait. A simple example being `Vector[Animal]` where `Animal` is a trait. However, it's unclear if either the type system doesn't support this yet, or I'm doing something wrong. I receive the error `Type Animal does not implement trait Default.` You can do something similar in Rust, but it requires `Box<dyn Animal>` since the structs are stack allocated vs. Moonbit structs are already heap allocated. Perhaps my Rust experience and the similarities are pushing towards patterns that aren't actually idiomatic in Moonbit?

### Moonbit

```rust
trait Animal  {
  make_sound(Self) -> String
}

struct Cat {

} derive(Default)

fn Cat::make_sound(self : Cat) -> String {
  "meow"
}

struct Dog {

} derive(Default)

fn Dog::make_sound(self : Dog) -> String {
  "woof"
}

struct Vec[T] {
  data : Array[T]
  mut length : Int
}

fn Vec::new[T : Default](size : Int) -> Vec[T] {
  { data: Array::make(size, T::default()), length: 0 }
}

fn push[T](self : Vec[T], value : T) -> Unit {
  self.data[self.length] = value
  self.length = self.length + 1
}

fn init {
  let animals : Vec[Animal] = Vec::new(2) // Type Animal does not implement trait Default.
  animals.push(Cat::{} as Animal)
  animals.push(Dog::{} as Animal)
}
```

<img width="588" alt="image" src="https://github.com/moonbitlang/moonbit-docs/assets/762949/b355a06b-66ff-45bf-8373-2d4cdf4a55d5">

### Equivalent Rust

```rust
trait Animal {
    fn make_sound(&self) -> String;
}

#[derive(Default)]
struct Cat {
    // cat specific state
}

impl Animal for Cat {
    fn make_sound(&self) -> String {
        "meow".to_string()
    }
}

#[derive(Default)]
struct Dog {
    // dog specific state
}

impl Animal for Dog {
    fn make_sound(&self) -> String {
        "woof".to_string()
    }
}

fn main() {
    let mut animals: Vec<Box<dyn Animal>> = Vec::new();
    animals.push(Box::new(Cat {}));
    animals.push(Box::new(Dog {}));
}
```

**Comment by jayphelps** [comment]
I think my Rust experience may be getting in the way of what's idiomatic in Moonbit. Perhaps the solution is for `Vec` to not require items implement `Default` at all, and instead internally just use `Option` to store the values? Although, using Option like this does presumably adds additional overhead in memory/cpu vs. just a bunch of nulls. That said, this seems to work:

```rust
trait Animal  {
  make_sound(Self) -> String
}

struct Cat {

} derive(Default)

fn Cat::make_sound(self : Cat) -> String {
  "meow"
}

struct Dog {

} derive(Default)

fn Dog::make_sound(self : Dog) -> String {
  "woof"
}

struct Vec[T] {
  data : Array[Option[T]]
  mut length : Int
}

fn Vec::new[T](size : Int) -> Vec[T] {
  { data: Array::make(size, None), length: 0 }
}

fn push[T](self : Vec[T], value : T) -> Unit {
  self.data[self.length] = Some(value)
  self.length = self.length + 1
}

fn init {
  let animals : Vec[Animal] = Vec::new(2)
  animals.push(Cat::{} as Animal)
  animals.push(Dog::{} as Animal)
}

```

Cc/ @bobzhang

**Comment by jayphelps** [comment]
Bump

**Comment by bobzhang** [comment]
we are in a holiday season, will get back to you later

**Comment by bobzhang** [comment]
@jayphelps my gut feeling is that Rust's Vec can not be implemented in a type safe way in the user land, it seems some unsafe primitives are needed to make Vec user experience better.
Questions on Option[T], we will do some optimizations, e.g, Option[String] is the same as String in the future

**Comment by bobzhang** [comment]
@jayphelps there is a work around like Rust:

try.moonbitlang.com/#2fff0b6f

```rust
type BoxAnimal Animal

fn BoxAnimal::default()->BoxAnimal{
  BoxAnimal(Cat::{})
}
```

**Comment by bobzhang** [comment]
>  I do worry that if you can't have trait polymorphism in this scenario it's gonna be a big headache for many other use cases. 

The `BoxAnimal` solution does not work for you? Note there is no runtime cost between BoxAnimal and Animal.

> Will this apply only to String and other primitives or also to more complex things like structs/traits?

Yes, we will unbox it as much as we can, but there are some corner cases, e.g, nested optionals and Option[Int]

**Comment by jayphelps** [comment]
> The BoxAnimal solution does not work for you? Note there is no runtime cost between BoxAnimal and Animal.

If I understand it correctly it seems fairly hacky, using Cat as the default value, is that right? In practice this won't work well because the Animal example was just contrived to simplify the issue at hand. In practice the structs I need to have polymorphism on have numerous fields, many of which there is no logical default value for. I could make up fake ones, but then the hackyness continues to bleed and it uses a bunch of excess memory.

**Comment by bobzhang** [comment]
@jayphelps FYI, we are providing an implementation of Vec with some builtin unsafe primitives so that such constraints are lifted

**Comment by bobzhang** [comment]
@jayphelps thanks for your feedback, we are rolling out a vector which lifts such limitation https://github.com/moonbitlang/core/pull/44/files

**Comment by jayphelps** [comment]
For posterity for those coming later, as of now this is now supported via `Array[&Animal]`

```moonbit
pub trait Animal {
  speak(Self) -> String
}

type Duck String

fn Duck::make(name : String) -> Duck {
  Duck(name)
}

impl Animal for Duck with speak(self) {
  "\{self._}: quack!"
}

type Fox String

fn Fox::make(name : String) -> Fox {
  Fox(name)
}

impl Animal for Fox with speak(_self) {
  "What does the fox say?"
}

fn main {
  let duck1 = Duck::make("duck1")
  let duck2 = Duck::make("duck2")
  let fox1 = Fox::make("fox1")
  let animals : Array[&Animal] = []
  animals.push(duck1)
  animals.push(duck2)
  animals.push(fox1)
  for animal in animals {
    println(animal.speak())
  }
}

```
