### ISSUE TITLE
[Feature Request] Specify FFI export name

### ISSUE THREAD

**Issue by fantix** [moonbitlang/moonbit-docs#152]
Given that MoonBit could do FFI import already:

```moonbit
fn import_func(param: Int) -> Int64 = "extern_module" "some/function"
```

It'll be nice if a name can be specified for exports too. Conceptual grammar per [discussion](https://taolun.moonbitlang.cn/t/topic/505):

```moonbit
pub fn on_complete "ns/on_message_complete" (ptr: Int) -> Int { ... }
```

compiles to:

```wat
 (func fantix/mmhttp/h11_ffi.on_complete.fn/2
  (export "ns/on_message_complete") (param $ptr i32) (result i32)
  ...)
```

* The same type constraints apply.
* Cross-module export is unnecessary atm.

This would allow the WIT bindgen to be less [hacky](https://gitee.com/fantix/componentize-mbt/blob/f2b20a8e5322c9dd6947a05b9ddcdfaa30347e69/crates/componentize/src/lib.rs#L42-45).

**Comment by bobzhang** [comment]
we are looking into this

**Comment by Yu-zh** [comment]
close as completed
