### ISSUE TITLE
Memory error with lots of string lterals

### ISSUE THREAD

**Issue by fantix** [moonbitlang/moonbit-docs#159]
* moon 0.1.0 (9e06fe3 2024-02-05) on x86_64 Darwin 23.3.0
* `--target wasm`

Refs [this commit](https://gitee.com/fantix/mmhttp/commit/985a22f2c0a91ee6758cfdefa45500dcf55ba013) where I created a lot of string literals, my `h11_native` test started to fail:

```
test h11_native ... FAILED
called `Result::unwrap()` on an `Err` valueerror while executing at wasm backtrace:
    0: 0x1c3d - <unknown>!<wasm function 82>
    1: 0x1f616 - <unknown>!<wasm function 947>

Caused by:
    wasm trap: wasm `unreachable` instruction executed
```

But it passes if a few literals were reverted to initialize in the old way (using Int arrays, not in the `(data (offset (i32.const 10000))`), so I guess this commit hit some MoonBit MVP limitation.

**Comment by peter-jerry-ye** [comment]
Thanks for the report. We have applied a quick fix. Could you please try again?

**Comment by fantix** [comment]
I can confirm the issue is now fixed. Thank you!
