### ISSUE TITLE
printing char beyond `U+10000` causes `moon run` to panic

### ISSUE THREAD

**Issue by shamiao** [moonbitlang/moonbit-docs#181]
the following code try getting `U+10000` from a string...

```
fn main {
  let s = "a\u{6587}\u{10000}\u{1F408}";
  let c = s.get(2);
  println(c); // `moon run` panics
  let buf = Buffer::make(4);
  c.debug_write(buf);
  let s = buf.to_string();
  println(s); // `moon run` panics
}
```

causes `moon run` to panic on `2024-04-08` windows and ubuntu-20.04 toolchain: (but doesn't panic on playground)

```
error: 'thread 'main' panicked at src\main.rs:32:21:
assertion failed: c >= 0xdc00 && c <= 0xdfff
```

a slightly different panic happens, if changes line 3 to `let c = s.get(3);` to get `U+1F408`:

```
error: 'thread 'main' panicked at src\main.rs:40:51:
called `Option::unwrap()` on a `None` value
```

**Comment by peter-jerry-ye** [comment]
All platform has issue:
```
```

**Comment by hackwaly** [comment]
`let c = s.get(2);` cause c is not a valid unicode char. You should combine surrogate pairs to a single char then print it.

**Comment by peter-jerry-ye** [comment]
What we can do is changing the `to_string` method for invalid chars, i.e., print '\u0800' in this case

**Comment by peter-jerry-ye** [comment]
By the way, you may need this:

`Char::from_int(0x10000 + (s.get(4).to_int() - 0xd800).lsl(10)  + (s.get(5).to_int() - 0xdc00)) |> println`

**Comment by shamiao** [comment]
> By the way, you may need this:
> 
> `Char::from_int(0x10000 + (s.get(4).to_int() - 0xd800).lsl(10) + (s.get(5).to_int() - 0xdc00)) |> println`

The behavior of `String::get(self, index)` (`O(1)` by word, instead of `O(n)` by unicode code point) is worth to mention in core docs.
