### ISSUE TITLE
Cannot use return in new Trait function body

### ISSUE THREAD

**Issue by mizchi** [moonbitlang/moonbit-docs#196]
TSIA

![image](https://github.com/moonbitlang/moonbit-docs/assets/73962/7e4e07ff-b7be-40bc-88cd-65447472a86f)

**Comment by peter-jerry-ye** [comment]
Could you please check if this has been fixed in yesterday's release?

**Comment by peter-jerry-ye** [comment]
The issue should have been fixed. Feel free to reopen it if it still occurs.
