### ISSUE TITLE
cross platform prebuild

### ISSUE THREAD

**Issue by edwinjhlee** [moonbitlang/moonbit-docs#203]
moonbit 社区的朋友，你们好:

我最近在 开发 x-cmd，里面的 pkg 体系 类似 nvm / asdf，可以快速安装语言运行时。
以 bun 为例: https://www.x-cmd.com/pkg/bun

我们对 wasm 也有长期关注，也引入了 wasmer 和 wastime，以及 wasmedge:
https://www.x-cmd.com/pkg/wasmtime

因此，从去年开始，我一直关注 moonbit，并充满期待。我发现当前的安装方式在 linux 只支持 ubuntu。但从论坛看来，好像应该支持了其它发行版。

我的问题是，现在官方能否提供多个平台的 prebuilt （我们可以放在 pkg） ？或者 安装方式（可以放在 install）。

我们的 install 体系，是将安装指令收集一起，方便用户调用。例如 https://www.x-cmd.com/install/lua

Regards,
Li Junhao
24-05-15

**Comment by peter-jerry-ye** [comment]
现在的安装脚本是否足够使用？

**Comment by edwinjhlee** [comment]
我们之前 就已经 将上述脚本 加了 install 了： https://cn.x-cmd.com/install/moonbit

关键是，linux 这边 只支持 ubuntu。

我们 的 pkg/env 体系 可以 理解为 nvm 之于 node，pyenv 之于 python；我们现在 已经 支持 主流的脚本语言引擎。用户可以 按需 升级 或者 降级 相应的 引擎。如果 我们 把 moonbit 加入到 pkg INDEX，那么 用户就可以 管理 moonbit 的各个 主要版本了。

**Comment by peter-jerry-ye** [comment]
脚本已经更新过了，只是其他发行版没有进行过任何测试。至于说版本的话，目前更新较为频繁。社区有moonup或multimoon等类似项目。

**Comment by edwinjhlee** [comment]
> 脚本已经更新过了，只是其他发行版没有进行过任何测试。至于说版本的话，目前更新较为频繁。社区有moonup或multimoon等类似项目。

好的。我们后面 留意 一下。谢谢。

**Comment by peter-jerry-ye** [comment]
@edwinjhlee 注意当前脚本是
```bash
# linux & mac
curl -fsSL https://cli.moonbitlang.cn/install/unix.sh | bash
# windows
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.cn/install/powershell.ps1 | iex
```

**Comment by edwinjhlee** [comment]
> @edwinjhlee 注意当前脚本是
> 
> ```shell
> # linux & mac
> curl -fsSL https://cli.moonbitlang.cn/install/unix.sh | bash
> # windows
> Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.cn/install/powershell.ps1 | iex
> ```

好的，收到。

**Comment by lunrenyi** [comment]
@peter-jerry-ye 你好，目前提供的 windows 安装脚本会破坏我的系统环境。 

- 描述：在 powershell 环境下，如果 **PATH 有改动（如 powshell rc 文件加载了目录、临时添加目录）**，运行 `Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.cn/install/powershell.ps1 | iex` 命令后，PATH 的全部改动会被保存到 **windows 环境变量注册表**

- 脚本中的相关命令: `[System.Environment]::SetEnvironmentVariable("PATH", "$MoonBin;$env:PATH", [System.EnvironmentVariableTarget]::User)`

**Comment by peter-jerry-ye** [comment]
@lunrenyi 感谢反馈，我们会改成从注册表中获取环境变量。
