### ISSUE TITLE
Outdated docs on Array?

### ISSUE THREAD

**Issue by mationai** [moonbitlang/moonbit-docs#204]
The README says `[1]` is an Array, but it seems to be `@vec.Vec` now and need to be typed to become an Array. Just want to make sure it's just outdated docs and not me misunderstanding.

**Comment by peter-jerry-ye** [comment]
We were renaming `Array` to `FixedArray` and `@vec.Vec` to `Array` to give the structures a more precise name. The migration with separated in two steps:
- Last week the syntax `[x, y, z, ...]` creates `@vec.Vec` by default, and adjust according to the context.
- This week we've renamed the structures.

In theory, the content should be correct now. Sorry for the misleading information.
