### ISSUE TITLE
WebAssembly.instantiate(): invalid value type

### ISSUE THREAD

**Issue by 1226085293** [moonbitlang/moonbit-docs#208]
main.mbt
```mbt
pub fn now() -> Int = "Date" "now"

fn main {
  let startTime = now()
  let mut value = 0
  for index = 0; index < 10000000; index = index + 1 {
    value = value + 1;
  }
  println(now() - startTime)
  // println(@lib.hello())
}
```
Usage:
```ts
// 读取 WebAssembly 文件
const wasmBuffer = fs.readFileSync("./wasm/main.wasm");

// 使用 WebAssembly.instantiate 直接实例化
//@ts-ignore
const wasmModule = await WebAssembly.instantiate(wasmBuffer, {
	Date: {
		now: () => Date.now(),
	},
	now: () => Date.now(),
});
```
Error: 
> Error instantiating WebAssembly module: CompileError: WebAssembly.instantiate(): invalid value type 0x77 @+12 {stack: 'CompileError: WebAssembly.instantiate(): invalid value type 0x77 @+12', message: 'WebAssembly.instantiate(): invalid value type 0x77 @+12'}

Note: There is no error if the now function is not used.

**Comment by peter-jerry-ye** [comment]
Can not reproduce. Are you using Node 22 that supports wasm gc?

**Comment by 1226085293** [comment]
MoonBit Project:
[MoonBit.zip](https://github.com/user-attachments/files/15588720/MoonBit.zip)

Test NodeJs Project:
[ts_test.zip](https://github.com/user-attachments/files/15588863/ts_test.zip)

![image](https://github.com/moonbitlang/moonbit-docs/assets/45589707/9e6e3317-b451-4c2a-93ef-2d30d7b6691d)

**Comment by peter-jerry-ye** [comment]
Node 20 does not support GC. It has to be enabled with an experimental flag, and the support was unstable. The support was added in Node 22.

**Comment by 1226085293** [comment]
> Node 20 does not support GC. It has to be enabled with an experimental flag, and the support was unstable. The support was added in Node 22.

I will try using Node22 later
