### ISSUE TITLE
建议开源这个代码块的react组件

### ISSUE THREAD

**Issue by npmstudy** [moonbitlang/moonbit-docs#211]
![image](https://github.com/moonbitlang/moonbit-docs/assets/26357769/43627d72-6173-4dee-8dd7-61d3906f265b)

可以让其他开发者使用这个组件，运行mbt代码。对mbt未来有一点帮助。甚至未来会出现，以此为出现的编辑器或ai类的产品

**Comment by Lampese** [comment]
+1

**Comment by peter-jerry-ye** [comment]
https://www.npmjs.com/package/@moonbit/moonpad-monaco

Reference: https://github.com/moonbitlang/moonbit-docs/blob/main/moonbit-tour/src/main.ts
