### ISSUE TITLE
中文编程语言为什么代码不能用中文写，看了下还是英文

### ISSUE THREAD

**Issue by qqxiaoteng** [moonbitlang/moonbit-docs#212]
建议关键词，保留用中文

**Comment by qqxiaoteng** [comment]
fn init {
  print("Hello world!") // OK
}

fn init {
  let x = 1
  // x // fail
  print(x) // success
}

改一下

函数 初始化{
打印("世界你好")
}

**Comment by qqxiaoteng** [comment]
编译器开源吗，没看到编译器

**Comment by jellyterra** [comment]
请问您所说的中文编程语言指哪个？
