### ISSUE TITLE
provide wasi api style like FFI interface exmaple

### ISSUE THREAD

**Issue by HerrCai0907** [moonbitlang/moonbit-docs#215]
Is the WASI style API supported by moonbit? for example provide a raw linear memory view via FFI.

**Comment by bobzhang** [comment]
@HerrCai0907 Does your host support https://github.com/WebAssembly/multi-memory, can you elaborate a little bit what APIs would you like to use?

**Comment by HerrCai0907** [comment]
For example wasi: https://github.com/WebAssembly/WASI/blob/main/legacy/preview1/witx/wasi_snapshot_preview1.witx

It provide an series API to operate file / socket ...

The API looks like:
```
  (@interface func (export "fd_readdir")
    (param $fd $fd)
    ;;; The buffer where directory entries are stored
    (param $buf (@witx pointer u8))
    (param $buf_len $size)
    ;;; The location within the directory to start reading
    (param $cookie $dircookie)
    ;;; The number of bytes stored in the read buffer. If less than the size of the read buffer, the end of the directory has been reached.
    (result $error (expected $size (error $errno)))
  )
```
It means moonbit should provide a raw linear memory offset to low level runtime and let low level runtime can read / write data from/to this linear memeory.

**Comment by peter-jerry-ye** [comment]
If you can run wasm-gc then you can embed wat instructions: https://github.com/peter-jerry-ye/wasi

**Comment by yamajik** [comment]
My wish is [WASIX](https://wasix.org) support. And WebGPU support would be much better.

**Comment by HerrCai0907** [comment]
> If you can run wasm-gc then you can embed wat instructions: https://github.com/peter-jerry-ye/wasi

But it is an incompatible solution. If I want to import several thing together, then I need to do integrate, extract the heap related code and reuse it.

**Comment by yamajik** [comment]
@HerrCai0907 Here are some approaches for your wish (tips: for now, all the following options have no wasm-gc support)

- Option 1: [extism](https://github.com/extism/extism) framework, seems extism team has started s new [PDK](https://github.com/gmlewis/moonbit-pdk) project for Moonbit
- Option 2: [wasmer](https://github.com/wasmerio/wasmer) runtime, a possible way that I have successfully injected wasm func in Moonbit by [wasmer-go-sdk](https://github.com/wasmerio/wasmer-go)
- Option 3: [wasmtime](https://github.com/bytecodealliance/wasmtime) runtime, a possible way as wasmer, but not tested
- Option 4: [wasmedge](https://github.com/WasmEdge/WasmEdge) runtime, a possible way as wasmer, but not tested

**Comment by yamajik** [comment]
I do successfully call some wasi methods over WasmEdge runtime, but unfortunately, only partly supported. Because there's no way to get the address of a pointer/object in MoonBit.
- Basic stub types are supported: Int, Uint, Float...
- Unsupported types: String, Array, Struct...

How to pass a string to wasi methods, `"wasi:logging/logging" "log"` as an example
- Here's the WIT file: https://github.com/WebAssembly/wasi-logging/blob/main/wit/logging.wit#L34
- Here's the wit-bindgen for Rust - https://github.com/bytecodealliance/wit-bindgen
- Here's the ffi definition in Rust generated by wit-bindgen
``` Rust
#[allow(unused_unsafe, clippy::all)]
/// Emit a log message.
///
/// A log message has a `level` describing what kind of message is being
/// sent, a context, which is an uninterpreted string meant to help
/// consumers group similar messages, and a string containing the message
/// text.
pub fn log(level: Level, context: &str, message: &str) {
    unsafe {
        let vec0 = context;
        let ptr0 = vec0.as_ptr().cast::<u8>();
        let len0 = vec0.len();
        let vec1 = message;
        let ptr1 = vec1.as_ptr().cast::<u8>();
        let len1 = vec1.len();
        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize) {
            ::core::panicking::panic("internal error: entered unreachable code")
        }
        wit_import(
            level.clone() as i32,
            ptr0.cast_mut(t,
            len0,
            ptr1.cast_mut(),
            len1,
        );
    }
}
```
- But in MoonBit, **it doesn't work for missing pointer/address features**
``` MoonBit
// ffi definitions for wasi logging - https://github.com/WebAssembly/wasi-logging/blob/main/wit/logging.wit#L34
fn wasi_log(level : Int, context_ptr: Int, context_offset: Int, message_ptr: Int, message_offset: Int) = "wasi:logging/logging" "log"

pub fn log(level : Level, context : Context, message : String) -> Unit {
  let context_bytes = context.0.to_bytes()
  let message_bytes = message.to_bytes()
  wasi_log(
    level.0,
    context_bytes.as_ptr(), // Error here, no such method in MoonBit `as_ptr`
    context_bytes.length(),
    message_bytes.as_ptr(), // Error here, no such method in MoonBit `as_ptr`
    message_bytes.length(),
  )
}
```

**Comment by peter-jerry-ye** [comment]
@yamajik We have inline wasm supported, which allows you to manipulate pointer/address. We will provide `wit-bindgen` very soon.

**Comment by peter-jerry-ye** [comment]
Notice that now `wit-bindgen` has MoonBit support and [peter-jerry-ye/wasi](https://github.com/peter-jerry-ye/wasi/tree/main) has full wasi preview 1 support for wasm linear.
