### ISSUE TITLE
Syntax doc is extremely out of date

### ISSUE THREAD

**Issue by bferguson3** [moonbitlang/moonbit-docs#229]
Almost none of the examples will compile and run. I can't learn the language like this so unfortunately I have nothing further to give. 

https://www.moonbitlang.com/docs/syntax/

**Comment by peter-jerry-ye** [comment]
The syntax is fine, but the runner is outdated.

**Comment by goflyboy** [comment]
按这个文档操作写一个helloworld,操作第五步，报下列错误，error: main is not a package

**Comment by bzy-debug** [comment]
> 按这个文档操作写一个helloworld,操作第五步，报下列错误，error: main is not a package

感谢反馈，这是因为我们前两周更新了新建项目的文件布局。

现在你可以使用

```
moon run src/main
```

来运行

**Comment by peter-jerry-ye** [comment]
With the new website <https://tour.moonbitlang.com> and <https://docs.moonbitlang.com>, the issue is solved.
