### ISSUE TITLE
Synchronize json schema from moon

### ISSUE THREAD

**Issue by peter-jerry-ye** [moonbitlang/moonbit-docs#279]
- Synchronize json schema
- Generate document
- CI that executes every tuesday

**Comment by peter-jerry-ye** [comment]
https://github.com/moonbitlang/moon/blob/main/crates/moonbuild/template/pkg.schema.json
https://github.com/moonbitlang/moon/blob/main/crates/moonbuild/template/mod.schema.json

**Comment by notch1p** [comment]
What about this?

https://github.com/notch1p/moonbit-docs/actions/runs/10345373718
