### ISSUE TITLE
Type corresponding the WebAssembly `i64` type

### ISSUE THREAD

**Issue by yfzhe** [moonbitlang/moonbit-docs#3]
It seems that the `int` type is mapped to `i32` in webassembly, and `float` type mapped to `f64` (which is a little inconsistent to me). As a language targets WebAssembly, why does it not have a type corresponding `i64` type (and `f32`, too)? 

But I found this language also use two different operators `+` and `+.` for integer and float addition. So more numeric types would mean more operators for arithmatic?

One more question: why not using webassembly text mode for the "instruction" panel in the playground? I think the text mode is more readable than binary code with comments.

**Comment by bobzhang** [comment]
`int64` will be supported.
`+` and `+.` is not needed, we only need `+` for numeric types, this will be fixed in the next couple of months.

**Comment by bobzhang** [comment]
Note this is put on hold since we are working on unboxed i64 support

**Comment by bobzhang** [comment]
Should be supported and rolled out next week
