### ISSUE TITLE
Editor outputs incorrect string representation of `Bytes`

### ISSUE THREAD

**Issue by tonyfettes** [moonbitlang/moonbit-docs#312]
Pick any of the editor on the documentation website [here](https://docs.moonbitlang.com) and modify the result as

```moonbit
fn main {
  let b1 : Bytes = b"abcd"
  println(b1) // true
}
```

It will output:

```plaintext
ac
```

while we expect it to output:

```moonbit
b"\x61\x62\x63\x64"
```

Reported by @Demonmasterlqx

**Comment by bobzhang** [comment]
note this bug only appears in the code mirror based IDE, I could not reproduce in https://try.moonbitlang.cn/

**Comment by peter-jerry-ye** [comment]
This is likely due to the out-of-dated moonbit-pad @bzy-debug
