### ISSUE TITLE
Doc error, `moon run main` should be `moon run src/main`

### ISSUE THREAD

**Issue by 2eha0** [moonbitlang/moonbit-docs#314]
I followed the document to start a new project:
https://www.moonbitlang.com/download/
<img width="867" alt="image" src="https://github.com/user-attachments/assets/a892f60c-36a4-4f18-a8b8-b216dc32f9e8">
>
and I got an error:
```
> moon run main
error: main is not a package
```
I finally realized it should be `moon run src/main`

**Comment by peter-jerry-ye** [comment]
@lijunchen What's the expected behavior?

**Comment by lijunchen** [comment]
> @lijunchen What's the expected behavior?

`moon run <fs path to the main package>`

**Comment by lijunchen** [comment]
> ...
> I finally realized it should be `moon run src/main`

@2eha0 Thanks for the feedback. We will support fuzzy matching for this.

**Comment by blvd20** [comment]
按照 download 页面的指引， 我除了遇到了这个问题外，在安装插件那一步之后还遇到了执行 `MoonBit:install latest moonbit toolchain` 的错误。 在升级到最新版本 vscode 后就没问题了。 可能存在插件和 vscode 版本不兼容的问题。 最好能在文档中，给一些提示。
