### ISSUE TITLE
Have you considered supporting shorthand syntax for top-level functions to return complex generic types?

### ISSUE THREAD

**Issue by orange-pig** [moonbitlang/moonbit-docs#315]
In the Moonbit's syntax definition, it is necessary to define the types of top-level functions. This becomes tricky when a function needs to return a complex generic type. Developers are essentially unable to infer the exact return value type of this object on their own, which can be a problem when using certain libraries in Rust development. Unfortunately, Rust only solves abbreviation for trait implementations but does not address inference for struct generic types. Therefore, sometimes one has to resort to writing a long chunk of code within a function, which pollutes the true intention of the function's implementation.

**Comment by peter-jerry-ye** [comment]
Do you have a concrete example?

And what's the relationship with Rust here?

**Comment by orange-pig** [comment]
> Do you have a concrete example?

A rust example:

**Layer** is a strcut in  this example.

```
fn getLayer() -> Layer<Layered<Layer<Layered<EnvFilter, Registry>, DefaultFields, Format<Full, OffsetTime<Vec<BorrowedFormatItem<'_>>>>>, Layered<EnvFilter, Registry>>, DefaultFields, Format<Full, OffsetTime<Vec<BorrowedFormatItem<'_>>>>, NonBlocking> {   
}
```

> And what's the relationship with Rust here?

After studying the moonbit documentation, I feel that moonbit's syntax brings a lot of new and modern designs. I personally think that there are some similarities between the writing style and rust, so I can't help but compare them together without causing any disputes.
I infer that in the actual moonbit project, there may also be complex generics similar to rust. So, I hope to ask whether my question has been considered here.

**Comment by orange-pig** [comment]
> And what kind of shorthand do you propose?您建议采用哪种速记法？

I embrace this syntax, using the auto keyword to indicate type inference.

```
fn getLayer() -> auto {
}
```
Another way, a keyword (like observed, some) is used to indicate a generic structure or type.

```
fn getLayer() -> observed Layer {
}
```

**Comment by Guest0x0** [comment]
There is a difference in design philosophy between MoonBit and Rust here. Types serve three purposes in a statically typed programming language:

1. prevent bugs
2. provide static information for optimization
3. serve as document to enhance program readability

while very precise type can express program property better, they are often too large and completely unreadable. This destroys purpose 3 above.

Back to the topic of inferring return type of toplevel functions: it is technically possible to infer return type of functions in MoonBit, and we already do so for local functions. But MoonBit still choose to enforce full type annotation on toplevel function, on purpose: type signatures of toplevel functions are very important document for a statically typed language, we want these signatures to be spelled out explicitly to enhance readability of MoonBit code. An exception is trait implementation, `impl Trait for Type with f(...) ...`, whose signature can be fully determined by the trait's definition and the self type of the implementation, and indeed MoonBit does not enforce type annotation there.

So what if the type really gets too long? That's probably not the encouraged way to write MoonBit code. We encourage users to keep their types short, concise and readable, even sometimes at the expense of less expressive/precise type. So adding shorthand to/automatically infer return type of toplevel function is somewhat against MoonBit's design philosophy here.

What if sometimes a very long type is just unavoidable? If the lengthy type is common enough, you can use the type alias feature to simplify signatures:
```swift
typealias MyType[T] = Layer1[Layer2[ ... LayerN[T] ... ]

fn f1(...) - > MyType[...]
fn f2(...) -> MyType[...]
```
