### ISSUE TITLE
[feat request] Show trait info in LSP completion

### ISSUE THREAD

**Issue by LittleJianCH** [moonbitlang/moonbit-docs#323]
It will be much helpful to show the trait info in LSP completion. 

For example, there's a function `write_object`:
```
pub fn Logger::write_object[Obj : Show](self : Logger, obj : Obj) -> Unit {
  obj.output(self)
}
```

Now, LSP will show info like this 
<img width="536" alt="截屏2024-11-05 14 37 19" src="https://github.com/user-attachments/assets/bc038e68-ec68-41fc-9093-04552776ef21">

It's unhelpful since I don't what `Obj` is here. I have to jump to the definition of `Logger::write_object` to get enough informations.

**Comment by Guest0x0** [comment]
fixed in latest release
