### ISSUE TITLE
文档顺序问题 - 下载界面

### ISSUE THREAD

**Issue by huifeidou** [moonbitlang/moonbit-docs#324]
## 现状 

问题入口:  https://www.moonbitlang.cn/download/

当前页面如图所示

![image](https://github.com/user-attachments/assets/c190001e-e9a8-423c-b486-cc7be10a8c9c)

在这里先让用户安装 VS Code MoonBit 插件 ，提到

> 第 4 步: 下载完成后，点击terminal，输入moon new hello ; code hello以创建并打开新项目。

如果直接按照这个文档当前的步骤执行会出现 moon 命令找不到的情况，具体执行情况如下

```
> moon new hello
moon: command not found
```

## 修改意见
顺序调整为 先展示  MoonBit CLI 工具 再展示 VS Code MoonBit 插件。

**Comment by peter-jerry-ye** [comment]
我们推荐用户通过VSCode插件形式安装，更为简便。

请确认第三步是否正确执行？

**Comment by peter-jerry-ye** [comment]
Related #327
