### ISSUE TITLE
教程中的两处问题

### ISSUE THREAD

**Issue by sunye-cn** [moonbitlang/moonbit-docs#327]
我正在学习MoonBit，根据官方教程 [https://www.moonbitlang.cn/download/](https://www.moonbitlang.cn/download/) 搭建MoonBit环境时遇到以下两个问题：

### 1. 描述：
在官方教程[https://www.moonbitlang.cn/download/](https://www.moonbitlang.cn/download/) 中给出的第四步，当前面的步骤都正确执行后，在VSCode的Terminal中输入`moon new hello`会报下面这种错误：
``` 
PS D:\moonbit> moon new hello
moon : 无法将“moon”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ moon new hello
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (moon:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException 
```
### 2. 原因：
因为首次安装会改变电脑的环境变量，但VSCode只有当打开窗口的时候才会加载环境变量，所以VSCode中Terminal的环境变量还是安装前的内容，所以无法识别。

### 3. 解决方式（三种方式，目的都是重新加载环境变量）：
- 在电脑终端安装，然后打开VSCode，运行`moon new hello`命令。
- 在VSCode安装，然后重启VSCode，运行`moon new hello`命令。
- 在VSCode安装，然后在Terminal输入以下命令，重新加载环境变量，再运行`moon new hello`命令。
    > $env:PATH = [System.Environment]::GetEnvironmentVariable("Path", [System.EnvironmentVariableTarget]::Machine) + ";" + [System.Environment]::GetEnvironmentVariable("Path", [System.EnvironmentVariableTarget]::User)

### 1. 描述：
在官方教程 [https://www.moonbitlang.cn/download/](https://www.moonbitlang.cn/download/) 中，在正确完成前四步之后，执行第五步时会报下面的错误：
```
PS D:\moonbit\hello> moon run main
error: main is not a package
```

### 2. 原因：
 `moon run main` 这个命令可能是过时的或者错误的。

### 3. 解决方式：
根据官方给出的另一个教程：[新手之旅](https://docs.moonbitlang.cn/tour) 中给出的`moon run src/main`命令就可以正确执行。
```
PS D:\moonbit\hello> moon run src/main
Hello, world!
```

**Comment by bzy-debug** [comment]
Should be fixed now, closed
