### ISSUE TITLE
Feature request: support `derive` for traits

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/moonbit-docs#342]
Context: https://github.com/gmlewis/moonbit-ray-tracer

In this repo, I was forced to write:

```moonbit
pub(open) trait Object {
  ...
  output(Self, Logger) -> Unit
  to_string(Self) -> String
}
```

instead of (preferred):

```moonbit
pub(open) trait Object {
  ...
} derive(Show)
```

in order to support `inspect!` in black-box unit tests, but the compiler doesn't allow it.
(Also, I wanted to add `op_equal` to support `assert_eq!` but couldn't get it to work with trait objects... but that's probably a different issue that is unrelated to this one.)

It might be nice to be able to derive any methods for traits, like `Show`, `Eq`, `FromJson`, `ToJson`, etc.

**Comment by peter-jerry-ye** [comment]
Transferring to moonbit-docs since it's a missing topic in document.
