### ISSUE TITLE
文档中首页程序入口小节的示例代码运行报错

### ISSUE THREAD

**Issue by yunnysunny** [moonbitlang/moonbit-docs#348]
[程序入口](https://docs.moonbitlang.cn/#%E7%A8%8B%E5%BA%8F%E5%85%A5%E5%8F%A3)运行 `RUN` 按钮时直接报错了：
```
Runtime Error: TypeError: a is not a function
```
![image](https://github.com/user-attachments/assets/039c79c3-0067-4877-aa3b-6784957c0093)

**Comment by peter-jerry-ye** [comment]
我们正在进行网站重构，这个组件之后应该不会再维护

我们之后会推出更好的交互式网站和静态文档网站。

**Comment by yunnysunny** [comment]
静待佳音，我看已经错了好久了

**Comment by peter-jerry-ye** [comment]
现在已经有 <tour.moonbitlang.com> 和 <docs.moonbitlang.com> 了。我们会逐步撤下原来的网站。
