### ISSUE TITLE
error: failed when building

### ISSUE THREAD

**Issue by wzzc-dev** [moonbitlang/moonbit-docs#350]
failed: moonc build-package -error-format json /home/chuang/minimoonbit-public/src/riscv/reg.mbt /home/chuang/minimoonbit-public/src/riscv/rv_asm.mbt /home/chuang/minimoonbit-public/src/riscv/asm_stringify.mbt /home/chuang/minimoonbit-public/src/riscv/emit.mbt -o /home/chuang/minimoonbit-public/target/wasm-gc/debug/build/riscv/riscv.core -pkg moonbitlang/minimbt/riscv -std-path /home/chuang/.moon/lib/core/target/wasm-gc/release/bundle -i /home/chuang/minimoonbit-public/target/wasm-gc/debug/build/closure/closure.mi:closure -i /home/chuang/minimoonbit-public/target/wasm-gc/debug/build/minimbt.mi:typing -pkg-sources moonbitlang/minimbt/riscv:/home/chuang/minimoonbit-public/src/riscv -target wasm-gc -g -source-map

         --  -- 
       /  //  / __--------_
      /  //  /_/            \
   ---      -                \ __
  / X        /        ____   /   )
  *_________/__/_____/______/ `--

Oops, the compiler has encountered an unexpected situation.
This is a bug in the compiler.

A bug report containing the error description and relevant code would be
greatly appreciated. You can submit the bug report here:

  https://github.com/moonbitlang/moonbit-docs/issues/new?labels=bug,ICE

Error: File "inlined_snapshot/_build/Typer.ml", line 3842, characters 13-19: Assertion failed

Compiler args: moonc build-package -error-format json /home/chuang/minimoonbit-public/src/riscv/reg.mbt /home/chuang/minimoonbit-public/src/riscv/rv_asm.mbt /home/chuang/minimoonbit-public/src/riscv/asm_stringify.mbt /home/chuang/minimoonbit-public/src/riscv/emit.mbt -o /home/chuang/minimoonbit-public/target/wasm-gc/debug/build/riscv/riscv.core -pkg moonbitlang/minimbt/riscv -std-path /home/chuang/.moon/lib/core/target/wasm-gc/release/bundle -i /home/chuang/minimoonbit-public/target/wasm-gc/debug/build/closure/closure.mi:closure -i /home/chuang/minimoonbit-public/target/wasm-gc/debug/build/minimbt.mi:typing -pkg-sources moonbitlang/minimbt/riscv:/home/chuang/minimoonbit-public/src/riscv -target wasm-gc -g -source-map

moonc version: v0.1.20241210+3258bad5b
error: failed when building

**Comment by peter-jerry-ye** [comment]
Minimal reproduction case:
```moonbit
fn init {
  for a, b, c in [1, 2, 3] {}
}
```

**Comment by lynzrand** [comment]
Fixed. Will be included in the next version.
