### ISSUE TITLE
`moon new hello` got `Permission denied (os error 13)`

### ISSUE THREAD

**Issue by hu-qi** [moonbitlang/moonbit-docs#353]
![image](https://github.com/user-attachments/assets/09c2de2c-86a7-42a1-b1be-6893e6110155)

I installed  moon by the VSCode , runn  ` MoonBit:install latest moonbit toolchain`

**Comment by hu-qi** [comment]
I use a other foloder， it's work.
like `cd ~ && moon new hello `

**Comment by peter-jerry-ye** [comment]
Do you have more details, like which operating system you are using and what architecture it is, where you are running (it looks like a devcontainer?)

**Comment by hu-qi** [comment]
> Do you have more details, like which operating system you are using and what architecture it is, where you are running (it looks like a devcontainer?)

Yes, It's a devcontainer. It's a problem with the cloud server. Creating folders is not allowed in the root path.Thanks!
![Snipaste_2024-12-17_11-16-38](https://github.com/user-attachments/assets/0dd19b17-b180-4045-8913-1aa86a106e79)

![Snipaste_2024-12-17_11-19-46](https://github.com/user-attachments/assets/7c384efd-644a-454a-8b43-86ced1b2079d)
