### ISSUE TITLE
Function Parameter Evaluation Order: Is it Necessary?

### ISSUE THREAD

**Issue by FlyCloudC** [moonbitlang/moonbit-docs#361]
In the documentation, it is stated that

> Labelled function can be supplied in any order. The evaluation order of arguments is the same as the order of parameters in function declaration.

However, this fixed parameter evaluation order prevents compiler optimization, and there don't seem to be many practical use cases. Even in cases where evaluation in a specific order is required, it can be achieved using multiple let statements.

**Comment by peter-jerry-ye** [comment]
This is useful when you want things like:

```moonbit
fn op_view[A](self : Array[A], start~ : Int = 0, end~: Int = self.length()) -> ArrayView[A]
```

And this sentence is just a clarification. What's your expectation?

**Comment by FlyCloudC** [comment]
I expect that only the "unprovided default parameters" are evaluated in order. For example, in the following code:

```moonbit
fn just_return(x : Int) -> Int {
  println(x)
  x
}

fn f(
  a~ : Int,
  b~ : Int,
  c~ : Int = just_return(b * 10),
  d~ : Int = just_return(c * 10)
) -> Unit {
  println("call f(a=\{a}, b=\{b}, c=\{c}, d=\{d})")
}

fn main {
  f(b=just_return(1), a=just_return(2))
}
```

only guarantees to output is

```
2
1
10
100
call f(a=2, b=1, c=10, d=100)   
```

or

```
1
2
10
100
call f(a=2, b=1, c=10, d=100) 
```

In this way, in the following situation, `b` can be calculated with priority, so as to release a register before calculating the `<very complex expression>)` (just like in C language).

```
let x = 11
f(
  a=<very complex expression>, // Suppose computing this expression requires a lot of registers
  b=x,
)
```

**Comment by Guest0x0** [comment]
1. the statement you quote is about the relationship between labelled application and positional application. For example, given `fn f(x~ : Int, y~ : Int)`, that statement says that `f(y=1, x=2)` is equivalent to `f(2, 1)` after erasing the labels. The evaluation order of labelled argument is now determined by the left-to-right evaluation order of positional arguments. So there's nothing special about labelled arguments here
2. So I guess what you want to ask is: why does MoonBit enforce left-to-right evaluation order for function application? In general MoonBit discourages undefined behavior. In terms of evaluation order of arguments:
    - if the arguments are pure, or have no effect conflict, than adjusting evaluation order is unobservable and will **not** violate the left-to-right specification. The compiler can do this even if the language spec requires left-to-right evaluation order
    - if the arguments do have effect conflict, changing evaluation order is behavior changing and will result in hard-to-debug issues.

    So the only benefit of making evaluation order UB is: when the compiler is unable to determine if the arguments have effect conflict, it can do unsafe optimizations as if the arguments don't have effect conflict. But if you are unlucky such optimization will result in behavior change and bugs. I don't think this behavior is desirable.
