### ISSUE TITLE
Why do moonbitlang language type keywords start with uppercase

### ISSUE THREAD

**Issue by conero** [moonbitlang/moonbit-docs#366]
I was very excited when I first saw news about the Moonbitlang language. And I often pay attention to the news updates on the official website, hoping that Moonbit can achieve success, although it will definitely be a difficult process.

But I have a very beginner's question on my end, why does the keyword type for moonbit start with a capital letter instead of [go](https://pkg.go.dev/builtin@go1.23.4), [rust](https://doc.rust-lang.org/std/index.html#primitives), [zig](https://ziglang.org/documentation/0.13.0/#Primitive-Types), and [v](https://docs.vlang.io/variables.html). The types of keywords starting with capital letters are as follows:

- Writing must follow "Shit+", while lowercase is more concise and faster to write (the latter is much simpler)
- Inconsistent style with other keywords such as fn, let, main, struct, etc

```rust
// moonbit
fn add(a : Int, b : Int) -> Int {
  let x : Int = 10 
  a + b + x
}

```

```go
// golang
func add(a int, b int) int {
	var x int = 10
	return a + b + x
}
```

```rust
// rust
fn add(a: i32, b: i32) -> i32 {
    let x: i32 = 10;
    a + b + x
}
```

> Finally, I hope Moonbitlang will continue to develop and become more concise, practical (ergonomic), and well liked by many people

**Comment by peter-jerry-ye** [comment]
They are not keywords. They are builtin types, and they follow the same naming convention as any other types.

**Comment by peter-jerry-ye** [comment]
> > They are not keywords. They are builtin types, and they follow the same naming convention as any other types.
> 
> However, it is still written in a similar style to `Double` when it actually writes the code or as the example provided on the website shows.

I don't see why that's a problem? `Int` / `Double` / `UInt` / ... are just builtin types, so they are treated the same as `Option` / `Result` or anything you define.

**Comment by peter-jerry-ye** [comment]
Again, they are not keywords, and you can effectively write the following (though it is confusing and should be discouraged):

```moonbit
type Double Bool

fn main {
  let a : Double = true
  let b : Double = not(true)
}
```
