### ISSUE TITLE
MoonCakes "Getting Started" URL 404

### ISSUE THREAD

**Issue by inkydragon** [moonbitlang/moonbit-docs#370]
1. Open https://mooncakes.io/
2. Click "Getting Started"
3. Jump to https://docs.moonbitlang.com/package-manage-tour

It should be https://docs.moonbitlang.com/en/latest/toolchain/moon/package-manage-tour.html

**Comment by peter-jerry-ye** [comment]
Thank you for your report! Will fix it asap.

**Comment by peter-jerry-ye** [comment]
Issue is fixed. Thanks again.
