### ISSUE TITLE
教程中的一处问题

### ISSUE THREAD

**Issue by wangjuwudi** [moonbitlang/moonbit-docs#372]
问题发生在 https://docs.moonbitlang.cn/#%E9%BB%98%E8%AE%A4%E9%94%99%E8%AF%AF%E7%B1%BB%E5%9E%8B

图一：
![moonbit-Bug](https://github.com/user-attachments/assets/4d2facb2-c07c-4d19-8a23-b94c3185511a)

图二（修正后代码）：
![moonbit](https://github.com/user-attachments/assets/6292e165-a63f-44af-a54b-7bd3c6b111db)

**Comment by peter-jerry-ye** [comment]
感谢反馈，我们很快会将 docs.moonbitlang.cn 的内容切换到最新的文档。

**Comment by wangjuwudi** [comment]
好的
