### ISSUE TITLE
文档 https://tour.moonbitlang.com/basics/test/index.html 中的 playground链接不存在

### ISSUE THREAD

**Issue by yunnysunny** [moonbitlang/moonbit-docs#373]
链接 https://tour.moonbitlang.com/basics/test/try.moonbitlang.com 打开后是 404

**Comment by peter-jerry-ye** [comment]
能请问下你是在哪里看到这个链接的吗？

**Comment by yunnysunny** [comment]
> 能请问下你是在哪里看到这个链接的吗？

![image](https://github.com/user-attachments/assets/aecd8c69-17a5-4ea7-a6df-6e6edb8c33bf)

**Comment by peter-jerry-ye** [comment]
看到了，感谢反馈
