### ISSUE TITLE
dark mode page text issue 

### ISSUE THREAD

**Issue by X7md** [moonbitlang/moonbit-docs#43]
look like jekyll-theme have text color issue when `prefers-color-scheme: dark` is true

<img width="960" alt="image" src="https://github.com/moonbitlang/moonbit-docs/assets/54203033/d472c759-4eed-4b34-97e6-b43a8ae517fb">

Text isn't readable.

**Comment by liweijian** [comment]
Thanks

**Comment by bzy-debug** [comment]
This should be fixed now.
Closed
