### ISSUE TITLE
Formatting: Parenthesis being removed from logical expressions

### ISSUE THREAD

**Issue by lucasavila00** [moonbitlang/moonbit-docs#44]
When the following is formatted:
```
idx_a == idx_b || (arg_a == arg_b && ret_a == ret_b)
```

it becomes:

```
idx_a == idx_b || arg_a == arg_b && ret_a == ret_b
``` 

Prettier transforms the non-parenthesis version to the one with parenthesis. And given the parenthesis version, prettier keeps it that way.

I like the formatting rule where expressions that combine operators of different precedence should have parenthesis.

**Comment by liweijian** [comment]
Thank you

**Comment by Yoorkin** [comment]
hi lucasavila00, thanks for your interest! It's better to print more readable code. At this stage we aim to make formatter print the code correctly, we will support this in future.
