### ISSUE TITLE
Cannot fix unused self warning

### ISSUE THREAD

**Issue by lucasavila00** [moonbitlang/moonbit-docs#46]
``` 
struct A {

}

pub func op_equal(self : A, _other : A) -> Bool {
  return false
}
```

it is impossible to fix the warning `Warning 002: Unused variable 'self'`.

In rust, not using self is not an error...

**Comment by liweijian** [comment]
Thanks, we will take a look

**Comment by HridoyHazard** [comment]
can i take this issue ?

**Comment by HridoyHazard** [comment]
@lucasavila00 hi can you point it out. i got a solution.
