### ISSUE TITLE
Arabic letters not rendering in string print 

### ISSUE THREAD

**Issue by abusaidm** [moonbitlang/moonbit-docs#47]
Amazing work team,

I tried adding arabic letters in the string and it printed garbage. (screenshot attached)

<img width="599" alt="image" src="https://github.com/moonbitlang/moonbit-docs/assets/10223047/32e06178-97b3-4991-8e6e-536baf47bc6b">

Code block in case you want to reproduce or test for

```
func init {
  // oop style method call
  "hello moonbit\n".print()
  "مرحبا moonbit".print()
}

```

output should look like the input in terms of drawing :)

**Comment by liweijian** [comment]
Thanks for your feedback, Moonbit currently supports Latin-1, CJK characters, Basic emoji. We will support more character sets in the future.

**Comment by pe200012** [comment]
> Thanks for your feedback, Moonbit currently supports Latin-1, CJK characters, Basic emoji. We will support more character sets in the future.

This is concerned about string printing, not identifiers. We may need to modify the runtime. cc @lijunchen

**Comment by bobzhang** [comment]
<img width="396" alt="Screenshot 2023-09-28 at 17 35 24" src="https://github.com/moonbitlang/moonbit-docs/assets/747051/e815d3d4-b854-48bc-ab7d-9b0945326579">


There are still some issues but basic printing should work now

**Comment by secext2022** [comment]
Thank you, it works !

The current implementation decode utf-8 bytes (of whole line) at LF (`\n`) char.
So you should print `\n` (or use `println()`) for it to work.

**Comment by peter-jerry-ye** [comment]
Closing the issue as it's fixed. Feel free to reopen if the issue persists.
