### ISSUE TITLE
Dark Mode: Tooltips have white text on white background

### ISSUE THREAD

**Issue by lucasavila00** [moonbitlang/moonbit-docs#48]
![image](https://github.com/moonbitlang/moonbit-docs/assets/12750442/6dacfddf-85b1-4f47-b4ed-f3c05fede6d2)

notice they show because I highlighted it

if I don't highlight it:

![image](https://github.com/moonbitlang/moonbit-docs/assets/12750442/f5e64ad1-8ef7-4642-9af2-68d16a20ddfb)

**Comment by liweijian** [comment]
Thanks for your feedback

**Comment by bzy-debug** [comment]
This should be fixed now.
Closed
