### ISSUE TITLE
Error: Bad wat format

### ISSUE THREAD

**Issue by chaihf1999** [moonbitlang/moonbit-docs#54]
I ran these code and get "Error: Bad wat format", is it a bug?

Here is the link: https://try.moonbitlang.com/#8c71031c2385976e9995ccf43b5aa2f1

```go
pub struct T {
  x : Int
}

pub func op_add(self : T, other : T) -> T {
  { x: self.x + other.x }
}

let a : T = { x: 0 }

let b : T = a + a

func init {
  "hello".print()
}
```

**Comment by liweijian** [comment]
Thanks, we will take a look at it

**Comment by liweijian** [comment]
This bug is fixed, wait for next release:)
