### ISSUE TITLE
print可以放在前边么！！！

### ISSUE THREAD

**Issue by yingjie52** [moonbitlang/moonbit-docs#59]
print放在前面好像更顺眼，一般都是动词+名词格式

**Comment by uinz** [comment]
这个语法可能是参考 `koka` 的 dot selection

https://koka-lang.github.io/koka/doc/book.html#sec-dot

我个人还是很喜欢的, 可以减少括号的嵌套,
代码风格整体会偏向链式调用风格. 可以提升整体可读性.

**Comment by bobzhang** [comment]
we are working on a built in package support, so we will have something like this in built-in package:
```
func print[X:Show](x : X) {
  x.to_string().print()
}
```

**Comment by yingjie52** [comment]
> 这个语法可能是参考 `koka` 的 dot selection
> 
> https://koka-lang.github.io/koka/doc/book.html#sec-dot
> 
> 我个人还是很喜欢的, 可以减少括号的嵌套, 代码风格整体会偏向链式调用风格. 可以提升整体可读性.

减少括号嵌套也可以这样：1.   print().***;       2.print.****    两者都兼顾了不是吗？符合逻辑又不用切换到括号

**Comment by yingjie52** [comment]
> we are working on a built in package support, so we will have something like this in built-in package:
> 
> ```
> func print[X:Show](x : X) {
>   x.to_string().print()
> }
> ```

那看后面有没有人反馈这个问题吧
