### ISSUE TITLE
moonbit-docs/examples/game_of_life/  build failed 

### ISSUE THREAD

**Issue by luoxuwei** [moonbitlang/moonbit-docs#64]
> moon version:

moon 0.1.0 (079caf9 2023-09-09)
moonc a2874403f 

> output:

moonbit-docs/examples/game_of_life/lib/game_of_life.mbt:23:29-23:39 The value identifier array_make is unbound.
moonbit-docs/examples/game_of_life/lib/game_of_life.mbt:23:56-23:60 This expression has type _/0, which is a unknown type and not a variant.
moonbit-docs/examples/game_of_life/lib/game_of_life.mbt:79:28-79:38 The value identifier array_make is unbound.
moonbit-docs/examples/game_of_life/lib/game_of_life.mbt:79:65-79:69 This expression has type _/0, which is a unknown type and not a variant.

**Comment by liweijian** [comment]
Thanks, we will take a look at it

**Comment by liweijian** [comment]
Fixed by: https://github.com/moonbitlang/moonbit-docs/commit/89ed8f2f9efdf6ebc9f6e405873cc62df7a9a58c
