### ISSUE TITLE
moon_build_system_tutorial.md comments

### ISSUE THREAD

**Issue by duselguy** [moonbitlang/moonbit-docs#75]
1) _*.pkg files: These are package descriptor files. ..._
The asterisk means any string. It should be moon.pkg, because it is the fixed name for such files.
2) Why the color text here:
![image](https://github.com/moonbitlang/moonbit-docs/assets/22796143/bc5a4e34-1332-4015-a6e2-06826c7fbb90)
May be escape control chars (?)
3) Contents of the [https://www.moonbitlang.com/docs/build-system-tutorial/](url) is not synchronized with moon_build_system_tutorial.md after the changes.

**Comment by liweijian** [comment]
Thanks
