### ISSUE TITLE
assert example fails

### ISSUE THREAD

**Issue by duselguy** [moonbitlang/moonbit-docs#78]
vladimir@vladimir-laptop:~$ moon version
moon 0.1.0 (6da2392 2023-09-14)
moonc 3eb987b84 /home/vladimir/.moon/bin/moonc

`vladimir@vladimir-laptop:~/Code/Moon/examples/assert$ moon run main
failed: moonc link-tast /home/vladimir/Code/Moon/examples/assert/target/build/lib/lib.tast /home/vladimir/Code/Moon/examples/assert/target/build/main/main.tast -o /home/vladimir/Code/Moon/examples/assert/target/build/main/main.wat
Fatal error: exception ("unsupported primitive" (fn @bool_to_string))
Raised at Base__Error.raise in file "src/error.ml" (inlined), line 9, characters 14-30
Called from Base__Error.raise_s in file "src/error.ml", line 10, characters 19-40
Called from Wasm_of_clam.compileExpr in file "lib/xml/clam/wasm_of_clam.ml", line 520, characters 44-70
Called from Stdlib__List.fold_right in file "list.ml", line 126, characters 16-37
Called from Wasm_of_clam.compileExpr.got in file "lib/xml/clam/wasm_of_clam.ml" (inlined), line 259, characters 31-63
Called from Wasm_of_clam.compileExpr in file "lib/xml/clam/wasm_of_clam.ml", line 301, characters 17-28
Called from Wasm_of_clam.compileFunc in file "lib/xml/clam/wasm_of_clam.ml", line 699, characters 4-42
Called from Basic__Lst.map in file "lib/basic/lst.ml", line 35, characters 15-19
Called from Wasm_of_clam.compile in file "lib/xml/clam/wasm_of_clam.ml", line 737, characters 4-61
Called from Dune__exe__Moon0_main.wasm_of_prog in file "bin/moon0_main.ml" (inlined), line 162, characters 2-47
Called from Dune__exe__Moon0_main in file "bin/moon0_main.ml", line 233, characters 12-78
vladimir@vladimir-laptop:~/Code/Moon/examples/assert$ moon run ./main
failed: moonc link-tast /home/vladimir/Code/Moon/examples/assert/target/build/lib/lib.tast /home/vladimir/Code/Moon/examples/assert/target/build/main/main.tast -o /home/vladimir/Code/Moon/examples/assert/target/build/main/main.wat
Fatal error: exception ("unsupported primitive" (fn @bool_to_string))
Raised at Base__Error.raise in file "src/error.ml" (inlined), line 9, characters 14-30
Called from Base__Error.raise_s in file "src/error.ml", line 10, characters 19-40
Called from Wasm_of_clam.compileExpr in file "lib/xml/clam/wasm_of_clam.ml", line 520, characters 44-70
Called from Stdlib__List.fold_right in file "list.ml", line 126, characters 16-37
Called from Wasm_of_clam.compileExpr.got in file "lib/xml/clam/wasm_of_clam.ml" (inlined), line 259, characters 31-63
Called from Wasm_of_clam.compileExpr in file "lib/xml/clam/wasm_of_clam.ml", line 301, characters 17-28
Called from Wasm_of_clam.compileFunc in file "lib/xml/clam/wasm_of_clam.ml", line 699, characters 4-42
Called from Basic__Lst.map in file "lib/basic/lst.ml", line 35, characters 15-19
Called from Wasm_of_clam.compile in file "lib/xml/clam/wasm_of_clam.ml", line 737, characters 4-61
Called from Dune__exe__Moon0_main.wasm_of_prog in file "bin/moon0_main.ml" (inlined), line 162, characters 2-47
Called from Dune__exe__Moon0_main in file "bin/moon0_main.ml", line 233, characters 12-78
`

After the changes (no more bool to string):
    abort("assertion failed: " + x.to_string() + "\n") => abort("assertion failed: " + "\n")
vladimir@vladimir-laptop:~/Code/Moon/examples/assert$ moon run ./main
error: error while executing at wasm backtrace:
    0:  0x685 - <unknown>!$assert/lib.assert_eq|Int|.fn/2
    1:  0x6b1 - <unknown>!*init*/3

Caused by:
    wasm trap: wasm `unreachable` instruction executed

P.S. The sample hello from the doc doesn't work too:
`vladimir@vladimir-laptop:~/Code/Moon/examples/hello$ moon check --watch

failed: moonc check /home/vladimir/Code/Moon/examples/hello/main/main.mbt -o /home/vladimir/Code/Moon/examples/hello/target/check/main/main.mi -pkg hello/main -i /home/vladimir/Code/Moon/examples/hello/target/check/lib/lib.mi -pkg-sources hello/main:/home/vladimir/Code/Moon/examples/hello/main -pkg-sources hello/lib:/home/vladimir/Code/Moon/examples/hello/lib
/home/vladimir/Code/Moon/examples/hello/main/main.mbt:2:16-2:21 Type String has no method print.
Had errors, waiting for filesystem changes...
`

**Comment by liweijian** [comment]
Thanks, we will take a look at it

**Comment by duselguy** [comment]
@liweijian
Kernel		: Linux 6.2.0-32-generic (x86_64)
Distribution		: Ubuntu 22.04.3 LTS

**Comment by liweijian** [comment]
Thanks for your feedback, this is a known issue and will be fixed in the next release:)

**Comment by duselguy** [comment]
@liweijian 
Few questions:
1) Where is the tracker of moonbit distro changes (to have the last version before to open an issue)?
2) Is Moonbit Weekly Update in moonbit forum the only such source?
3) Do you plan to do regression testing (at least based on the samples from _examples_) before deploying each new version of moonbit ("hello world" snippet should work in any release including alpha)?

Thank you in advance

**Comment by liweijian** [comment]
@duselguy Thanks

1. We will create a CONTRIBUTING.md next week
2. You can also follow our twitter : https://twitter.com/moonbitlang
3. Yeah, you are right. We will put the demos(https://github.com/moonbitlang/moonbit-docs/tree/main/examples) into our regression testing pipeline.

**Comment by duselguy** [comment]
@liweijian 
Thank you!
I'm suggesting the CONTRIBUTING.md as the list of the entries with slightly truncated `moon version` output:
moon 0.1.0 (6da2392 2023-09-14) moonc 3eb987b84
In assumptions:
1) The hex values are unique and the date is the date of the distro creation.
2) The new (last) version is added to the top of the list to save the history of the distro changes.
3) The last version (top in the list) includes the changes for all **closed** issues.
P.S. Have no ideas how to separate MacOS and Ubuntu.
P.P.S. Somewhere twitter is available only through VPN.
