### ISSUE TITLE
Vscode plugin cannot identify package

### ISSUE THREAD

**Issue by QizhengMo** [moonbitlang/moonbit-docs#80]
vscode plugin version v0.1.197
OS: wsl2 ubuntu
moon ver: moon 0.1.0 (6da2392 2023-09-14)

reproduce steps:
download from https://www.moonbitlang.com/download/
moon new hello
open project with vscode

![image](https://github.com/moonbitlang/moonbit-docs/assets/54135657/9aad9bd4-bffd-46b3-9157-c84a98acab54)

**Comment by duselguy** [comment]
@QizhengMo 
(Unfortunately) Moonbit Language extension in vscode requires (?) the command "moon check --watch" that doesn't work now (see issue #78 ).
P.S. Please, add moonbit version with command "moon version" in your issue.

**Comment by lijunchen** [comment]
I noticed in your screenshot that there is only `target/build` and no `target/check`. You can upgrade to the latest version, and then run `moon check`.

**Comment by duselguy** [comment]
@liweijian 
@lijunchen 
Should moon_build_system_tutorial.md changed according to #84 ?
P.S. `Type String has no method print.`(?)
