### ISSUE TITLE
moon command cant work on may macbook

### ISSUE THREAD

**Issue by yyz945947732** [moonbitlang/moonbit-docs#81]
<img width="309" alt="image" src="https://github.com/moonbitlang/moonbit-docs/assets/47586954/cc89dd7f-fe29-47a4-b0f5-53328d3e6153">

<img width="341" alt="image" src="https://github.com/moonbitlang/moonbit-docs/assets/47586954/f4ec076d-f94e-4aa0-a600-54895dd7e11c">

**Comment by liweijian** [comment]
Intel CPU is not support yet
