### ISSUE TITLE
Is this not open-source?

### ISSUE THREAD

**Issue by glyh** [moonbitlang/moonbit-docs#82]
As title, thanks.

**Comment by bobzhang** [comment]
@glyh thanks for your interest. Moonbit is still in the phase of internal testing, there are large structural changes every week, we would like to stay focused at this moment. We will make the source public available once we reach a beta status (expected to be the end of Q2 next year).

**Comment by pannous** [comment]
can you reopen as tracking issue?

**Comment by glyh** [comment]
No push, but @bobzhang could you provide some updates? Thanks!

**Comment by tv42** [comment]
]It seems like you're now claiming to be open source, while the license is a source-available non-commercial use only SSPL.

https://www.moonbitlang.com/blog/compiler-opensource

> Why are we open-sourcing the Wasm backend?

> Modifications to the compiler are allowed for non-commercial purposes.

Please either stop saying "open source", or use an actual open source license.

**Comment by glyh** [comment]
They have their own license here, I haven't read it:

https://github.com/moonbitlang/moonbit-compiler/blob/main/LICENSE.TXT
