### ISSUE TITLE
Vscode plugin invalid type (?)

### ISSUE THREAD

**Issue by duselguy** [moonbitlang/moonbit-docs#88]
Ubuntu: 22.04.1
moon version: moon 0.1.0 (e1568eb 2023-09-19) moonc 526faad5e
Extension Version: v0.1.217
VSCode Version: 1.82.2

Slightly changed snippet from _examples_:
![Screenshot at 2023-09-26 02-02-21](https://github.com/moonbitlang/moonbit-docs/assets/22796143/b7cf280d-c1c8-4783-ad3d-967df53b4c10)
Why the type is `Int` not `Bool` ?

**Comment by peter-jerry-ye** [comment]
I think this issue has been fixed and it should display `(Int, Int) -> Bool` for now. Feel free to reopen if the issue still exists.
