### ISSUE TITLE
希望能扩展到数据分析，量化交易领域

### ISSUE THREAD

**Issue by wangwei123** [moonbitlang/moonbit-docs#90]
希望moonbit能扩展到数据分析，量化交易领域，语言简洁达到python水平，性能达到golang, rust水平，最好golang能做的moonbit都能做

**Comment by liweijian** [comment]
GitHub issues are not the appropriate place to debug your specific project, but should be reserved for filing bugs and feature requests.

Feel free to share your thoughts in our forum: https://taolun.moonbitlang.cn/
